### ISSUE TITLE
We are trying mummergpu on aws V100 GPU for long reads

### ISSUE THREAD

**Issue by harisankarsadasivan** [rmtheis/mummergpu#2]
Observing long reads of 9kb is 1.2x slower than an equivalent total basepair version of short reads on GPU dataset while 18kb long read dataset is 1.83x slower than its equivalent short read dataset. We figured out that V100 has much higher l1 and l2 caches than 8800. Is there any parameter that we could change to optimize mummergpu for longer reads on the powerful v100?

**Comment by rmtheis** [comment]
Sorry, I don't know and I can't help with this question.
